### PR TITLE
fix(platform resolver): determine if on macos using os.name instead of uname -a

### LINKED ISSUE #837: (platform resolver): Incorrectly identifies MacOS system if hostname contains "darwin" or "macos"
**Describe the bug**
https://github.com/aws-greengrass/aws-greengrass-nucleus/blob/8a9bd022c7a1da82012eec4a006839d7b7e36f70/src/main/java/com/aws/greengrass/config/PlatformResolver.java#L103

Uses `uname -a` which includes the hostname. If the hostname includes "darwin" the PlatformResolver will incorrectly identify the OS as Mac OSX.

**To Reproduce**
Change hostname to 'darwin' and launch Greengrass

**Expected behavior**
PlatformResolver shouldn't be resolving Linux machines with a hostname containing "darwin" to MacOSX

**Actual behavior**
Tell us what actually happened.

**Environment**
 - OS: Jetson Nano, running Ubuntu.
 - JDK version:
 - Nucleus version:

**Additional context**

E.g. what is the impact of the bug?

### PR DESCRIPTION
**Pull request by MikeDombo**
**Issue #, if available:**
Closes #837 

**Description of changes:**
Instead of using `uname -a` to determine the platform, switch to using `os.name` from the Java system properties.

**Why is this change necessary:**
`uname -a` contains the hostname in the output, so if the hostname was "darwin" or "macos" we were incorrectly identifying the machine as a mac.

**How was this change tested:**
Validate that on macos the os.name property is "Mac OS X"

Verified that we detect macos and linux correctly, and even after setting the hostname to "darwin" it still detects correctly.

**Any additional information or context required to review the change:**

**Checklist:**
 - [ ] Updated the README if applicable
 - [ ] Updated or added new unit tests
 - [ ] Updated or added new integration tests
 - [ ] Updated or added new end-to-end tests

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by shaguptashaikh — COMMENTED** [review]
Don't we need to change `Platform.getInstance()` as well? https://github.com/aws-greengrass/aws-greengrass-nucleus/blob/main/src/main/java/com/aws/greengrass/util/platforms/Platform.java#L48

**Comment by MikeDombo** [comment]
> Don't we need to change `Platform.getInstance()` as well? https://github.com/aws-greengrass/aws-greengrass-nucleus/blob/main/src/main/java/com/aws/greengrass/util/platforms/Platform.java#L48

Yes, just updated that as well.

File: src/main/java/com/aws/greengrass/config/PlatformResolver.java [hunk 1]
```diff
@@ -94,22 +94,22 @@ public PlatformResolver(DeviceConfiguration deviceConfiguration) {
...
-
-            if (sysver.contains("darwin")) {
-                return OS_DARWIN;
-            }
-            if (Files.exists(Paths.get("/proc"))) {
-                return OS_LINUX;
-            }
-        } catch (IOException | InterruptedException e) {
-            logger.error("Error trying to determine OS", e);
+        String osName = System.getProperty("os.name").toLowerCase();
```
Comment (fengwa-aws) [inline src/main/java/com/aws/greengrass/config/PlatformResolver.java:107]: Do you know how the `os.name` property is set?

Comment (MikeDombo) [reply src/main/java/com/aws/greengrass/config/PlatformResolver.java:107]: It is builtin to the JVM.

**Review by shaguptashaikh — APPROVED** [review]

**Review by fengwa-aws — DISMISSED** [review]

File: src/main/java/com/aws/greengrass/config/PlatformResolver.java (hunk 1 above)
Comment (MikeDombo) [reply src/main/java/com/aws/greengrass/config/PlatformResolver.java:107]: https://github.com/openjdk/jdk/blob/9604ee82690f89320614b37bfef4178abc869777/src/java.base/macosx/native/libjava/java_props_macosx.c#L234-L235

https://github.com/openjdk/jdk/blob/9604ee82690f89320614b37bfef4178abc869777/src/java.base/unix/native/libjava/java_props_md.c#L403

**Review by fengwa-aws — APPROVED** [review]

**Review by shaguptashaikh — APPROVED** [review]

**Review by philcali — APPROVED** [review]

**Review by K-AWS — APPROVED** [review]
